services:
  mysqldb:
    image: mysql/mysql-server:latest-aarch64
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - backend
    volumes:
      - mysqlvolume:/var/lib/mysql
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080
    env_file: .env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://mysqldb:3306/$MYSQL_DATABASE",
            "spring.datasource.username": "$MYSQL_USER",
            "spring.datasource.password": "$MYSQL_PASSWORD",
            "spring.jpa.hibernate.ddl-auto": "update"
          }'
    networks:
      - backend

networks:
  backend:

volumes:
  mysqlvolume: