services:
  db:
    image: mysql/mysql-server:latest-aarch64
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - backend
  api:
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://db:3306/$MYSQL_DATABASE",
            "spring.datasource.username": "$MYSQL_USER",
            "spring.datasource.password": "$MYSQL_PASSWORD",
            "spring.jpa.hibernate.ddl-auto": "update"
          }'
    networks:
      - backend

networks:
  backend:
