services:
  mysql5:
    image: mysql/mysql-server:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=secret2
