services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=secret2
